### ISSUE TITLE
Compression and Keep Input Artifacts

### ISSUE THREAD

**Issue by emikuszewski-pivotal** [dbbaskette/gpdb-sandbox#1]
* unknown configuration key: "compression"
* unknown configuration key: "keep_input_artifacts"

I just removed these two lines and it built fine.

**Comment by dbbaskette** [comment]
Those work fine for me,  but shouldn't change the overall output that much.    compression should change the amount of compression and make the output a bit smaller.   keep_input_artifacts kept the uncompressed image as well....I should probably just remove that.  I had it in for testing.
